project:
  type: website
  output-dir: docs

website:
  title: "**Akbar Ali**"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Conference.qmd
        text: Publications
      - href: Teaching.qmd   # <-- added here
        text: Teaching
      - href: Project.qmd
        text: Projects
      - href: gallery.qmd
        text: Gallery
      - href: files/CV.pdf
        text: CV

format:
  html:
    theme: litera
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap
    css: Styles.css  # Link to custom CSS

execute:
  freeze: auto
