---
title: "Projects and Workshops" 
format: html 
---

## Projects

1. **M.Tech 2021**  
   **Topic:** Prediction Model for Parkinson's Disease  
   **Advisor:** Dr. Saiyed Umer, Assistant Professor, Dept. of CSE, Aliah University, Kolkata 700156.

2. **B.Tech 2019**  
   **Topic:** Design of Home Automation using IoT  
   **Advisor:** Dr. Zeenat Rehena, Assistant Professor, Dept. of CSE, Aliah University, Kolkata 700156.

---

## Workshops

1. Attained the 3D Vision Summer School, held at IIIT Bangalore, India, from June 22 to June 28, 2024 [In-Person].  
   The program offered in-depth exposure to Deep Learning techniques and their applications in 3D Vision, featuring lectures, hands-on sessions, and discussions led by leading researchers in the field.

2. Attained Vishveshvarya Workshop at IIT Mandi in May 2024, focused on cutting-edge knowledge presentations and talks designed for all "Vishveshvarya phd scheme" candidates.

3. Participated in National Seminar on “Preparation & Publication of Research Articles” organized by Department of Computer Science and Engineering, Aliah University, Kolkata on 18th March 2019.

4. Participated in National Seminar on “Mathematical Modelling and its Application in Natural and Engineering Science (NSMMANES-2019)” organized by Department of Mathematics and Statistics, Aliah University, Kolkata on 25th March 2019.

---

## Experimental Work

1. **3D geophysical image translated into photorealistic virtual outcrop geology using generative adversarial networks**  
   *Feb 2024 - Jan 2025*  
   - Translated 3D geophysical images into photorealistic virtual outcrop geology using generative adversarial networks (GANs).  
   - Developed a methodology enabling the generation of diverse crop images at varying altitudes.

2. **Smart Farming of Cotton Using Aerial Imagery and Computer Vision**  
   *Jun 2023 - Jan 2024*  
   - We delve into the intricate relationship between weather conditions and crop health and the impact of different insects on cotton fields by harnessing the power of technology to revolutionize cotton farming practices. This holistic approach empowers us to provide farmers with actionable insights for optimized decision-making.  
   - Conducted weekly aerial image acquisition missions at varying altitudes (10m, 15m, and 115m) from July 1, 2023, to December 30, 2023. This allows us to comprehensively capture the entire growth cycle of the cotton crop, from the initial stages to the development of buds.

---

## Field Visits

### Drone Data Acquisition for Mineral and Rock Analysis  
*Department: Earth Science*

| **Place** | **Month/Year** |
|-----------|----------------|
| Ladakh    | May 2023       |
| Alibag    | August 2024    |
| Anjar     | November 2024  |

### Smart City and Transport Evaluation  
*Department: Computer Science*

| **Place**    | **Month/Year** |
|--------------|----------------|
| Silvassa     | July 2024      |
| Aurangabad   | July 2024      |
